#!/bin/bash
./SRBMiner-MULTI --algorithm curvehash --pool stratum+tcp://curvehash.mine.zergpool.com:3343 --wallet DFELbxWYubXQy5YvsEFrm3jZ48HBKfAopw.srbX --password c=DOGE,mc=PLSR --keepalive true
#./SRBMiner-MULTI --algorithm minotaurx --pool stratum+tcp://minotaurx.mine.zergpool.com:7019 --wallet DFELbxWYubXQy5YvsEFrm3jZ48HBKfAopw.srbX --password c=DOGE,mc=LCC --keepalive true
